# This file controls the settings for your Quarto template

# website settings
website:
  title: "UiB Collaborative Platform for GIS/RS"                               
  image: img/my_image.jpg
  search: false
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    
    # your sub-pages
    left:
      - href: seminars.qmd
        text: Monthly Seminar Series
      - href: uavworkshop.qmd
        text: UaV and RS Workshop
    

# Don't touch unless you know what you are doing :) ------------
  page-footer: 
    left: |
      <div id="fixed-copyright">© 2025 Augusto Lima</div>
    right: |
      <span class="faux-block">
        <img src="img/uva.jpg" alt="left Logo" style="height: 40px; vertical-align: middle;">
        <img src="img/uib.png" alt="center Logo" style="height: 40px; vertical-align: middle;">
        <img src="img/trond.jpg" alt="right Logo" style="height: 40px; vertical-align: middle;">
        <img src="img/bjerknes.webp" alt="last Logo" style="height: 40px; vertical-align: middle;">
      </span>

project:
  type: website
  output-dir: docs

  preview:
    browser: true
    watch-inputs: true
    navigate: true

format:
  html:
    fontsize: 1.3em
    theme: 
      - pulse
      - styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true